# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design_interfaces.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1119, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("\n"
"background-color: rgb(0, 0, 255);")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_header.setStyleSheet("QFrame{\n"
"    border-bottom:1px solid #000;\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.main_header.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.title_bar_container = QtWidgets.QFrame(self.main_header)
        self.title_bar_container.setStyleSheet("")
        self.title_bar_container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar_container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar_container.setObjectName("title_bar_container")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.title_bar_container)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.left_menu_toogle = QtWidgets.QFrame(self.title_bar_container)
        self.left_menu_toogle.setMinimumSize(QtCore.QSize(50, 0))
        self.left_menu_toogle.setMaximumSize(QtCore.QSize(50, 50))
        self.left_menu_toogle.setStyleSheet("QFrame{\n"
"    background-color:#000\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding:5px 10px;\n"
"    border:none;\n"
"    border-radius:5px;\n"
"    background-color:#000;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.left_menu_toogle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toogle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toogle.setObjectName("left_menu_toogle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.left_menu_toogle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_toogle = QtWidgets.QPushButton(self.left_menu_toogle)
        self.btn_toogle.setMinimumSize(QtCore.QSize(50, 40))
        self.btn_toogle.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/resources/icons/cil-menu.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_toogle.setIcon(icon)
        self.btn_toogle.setIconSize(QtCore.QSize(24, 24))
        self.btn_toogle.setObjectName("btn_toogle")
        self.horizontalLayout_4.addWidget(self.btn_toogle)
        self.horizontalLayout_5.addWidget(self.left_menu_toogle)
        self.title_bar = QtWidgets.QFrame(self.title_bar_container)
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_5.addWidget(self.title_bar)
        self.horizontalLayout_2.addWidget(self.title_bar_container)
        self.top_right_btn = QtWidgets.QFrame(self.main_header)
        self.top_right_btn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.top_right_btn.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(120, 120, 120);\n"
"}")
        self.top_right_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_right_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btn.setObjectName("top_right_btn")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btn)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimizeButton = QtWidgets.QPushButton(self.top_right_btn)
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setStyleSheet("")
        self.minimizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/resources/icons/cil-minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon1)
        self.minimizeButton.setIconSize(QtCore.QSize(24, 24))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.closeButton = QtWidgets.QPushButton(self.top_right_btn)
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("")
        self.closeButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/resources/icons/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon2)
        self.closeButton.setIconSize(QtCore.QSize(24, 24))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_2.addWidget(self.top_right_btn)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("")
        self.main_body.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        self.left_side_menu.setMinimumSize(QtCore.QSize(0, 0))
        self.left_side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_side_menu.setStyleSheet("QFrame{\n"
"    background-color:#000\n"
"}\n"
"\n"
"QPushButton{\n"
"    padding:20px 5px;\n"
"    border:none;\n"
"    border-radius:10px;\n"
"    background-color:#000;\n"
"    color:#fff;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(0, 92, 157);\n"
"}")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_menu_top_button = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_top_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_top_button.setObjectName("left_menu_top_button")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_menu_top_button)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_home = QtWidgets.QPushButton(self.left_menu_top_button)
        self.btn_home.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_home.setStyleSheet("background-image: url(:/newPrefix/resources/icons/cil-home.png);\n"
"background-repeat:none;\n"
"padding-left:50px;\n"
"background-position:center left;")
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_3.addWidget(self.btn_home)
        self.btn_informasi = QtWidgets.QPushButton(self.left_menu_top_button)
        self.btn_informasi.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_informasi.setStyleSheet("background-image: url(:/newPrefix/resources/icons/cil-newspaper.png);\n"
"background-repeat:none;\n"
"padding-left:50px;\n"
"background-position:center left;")
        self.btn_informasi.setObjectName("btn_informasi")
        self.verticalLayout_3.addWidget(self.btn_informasi)
        self.verticalLayout_2.addWidget(self.left_menu_top_button, 0, QtCore.Qt.AlignTop)
        self.btn_setting = QtWidgets.QPushButton(self.left_side_menu)
        self.btn_setting.setMinimumSize(QtCore.QSize(100, 0))
        self.btn_setting.setStyleSheet("background-image: url(:/newPrefix/resources/icons/cil-settings.png);\n"
"background-repeat:none;\n"
"padding-left:50px;\n"
"background-position:center left;")
        self.btn_setting.setObjectName("btn_setting")
        self.verticalLayout_2.addWidget(self.btn_setting)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_item = QtWidgets.QFrame(self.main_body)
        self.center_main_item.setMinimumSize(QtCore.QSize(70, 0))
        self.center_main_item.setStyleSheet("")
        self.center_main_item.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.center_main_item.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_item.setObjectName("center_main_item")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.center_main_item)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_item)
        self.stackedWidget.setLineWidth(-2)
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.home.setObjectName("home")
        self.frame = QtWidgets.QFrame(self.home)
        self.frame.setGeometry(QtCore.QRect(120, 100, 300, 300))
        self.frame.setMinimumSize(QtCore.QSize(300, 300))
        self.frame.setMaximumSize(QtCore.QSize(300, 300))
        self.frame.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.original_image = QtWidgets.QLabel(self.frame)
        self.original_image.setGeometry(QtCore.QRect(10, 10, 280, 280))
        self.original_image.setMinimumSize(QtCore.QSize(280, 280))
        self.original_image.setMaximumSize(QtCore.QSize(280, 280))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(40)
        self.original_image.setFont(font)
        self.original_image.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.original_image.setScaledContents(True)
        self.original_image.setAlignment(QtCore.Qt.AlignCenter)
        self.original_image.setObjectName("original_image")
        self.frame_2 = QtWidgets.QFrame(self.home)
        self.frame_2.setGeometry(QtCore.QRect(550, 100, 300, 300))
        self.frame_2.setMinimumSize(QtCore.QSize(300, 300))
        self.frame_2.setMaximumSize(QtCore.QSize(300, 300))
        self.frame_2.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.img_after = QtWidgets.QLabel(self.frame_2)
        self.img_after.setGeometry(QtCore.QRect(10, 10, 280, 280))
        self.img_after.setMinimumSize(QtCore.QSize(280, 280))
        self.img_after.setMaximumSize(QtCore.QSize(280, 280))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(30)
        self.img_after.setFont(font)
        self.img_after.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.img_after.setAlignment(QtCore.Qt.AlignCenter)
        self.img_after.setObjectName("img_after")
        self.frame_3 = QtWidgets.QFrame(self.home)
        self.frame_3.setGeometry(QtCore.QRect(20, 20, 991, 40))
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame_3.setStyleSheet("background-color: rgb(200, 200, 200);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_browse = QtWidgets.QPushButton(self.frame_3)
        self.btn_browse.setMinimumSize(QtCore.QSize(30, 30))
        self.btn_browse.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.btn_browse.setFont(font)
        self.btn_browse.setStyleSheet("")
        self.btn_browse.setObjectName("btn_browse")
        self.horizontalLayout_7.addWidget(self.btn_browse)
        self.path_dir = QtWidgets.QLabel(self.frame_3)
        self.path_dir.setMinimumSize(QtCore.QSize(0, 25))
        self.path_dir.setMaximumSize(QtCore.QSize(16777215, 25))
        self.path_dir.setStyleSheet("padding-left:2px;\n"
"background-color: rgb(255, 255, 255);")
        self.path_dir.setObjectName("path_dir")
        self.horizontalLayout_7.addWidget(self.path_dir)
        self.frame_4 = QtWidgets.QFrame(self.home)
        self.frame_4.setGeometry(QtCore.QRect(20, 420, 1001, 63))
        self.frame_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.frame_4)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.hasil_deteksi = QtWidgets.QLabel(self.frame_4)
        self.hasil_deteksi.setMinimumSize(QtCore.QSize(300, 0))
        self.hasil_deteksi.setMaximumSize(QtCore.QSize(500, 16777215))
        self.hasil_deteksi.setAlignment(QtCore.Qt.AlignCenter)
        self.hasil_deteksi.setObjectName("hasil_deteksi")
        self.verticalLayout_5.addWidget(self.hasil_deteksi, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.home)
        self.informasi = QtWidgets.QWidget()
        self.informasi.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.informasi.setObjectName("informasi")
        self.webEngineView = QtWebEngineWidgets.QWebEngineView(self.informasi)
        self.webEngineView.setGeometry(QtCore.QRect(10, 0, 1021, 511))
        self.webEngineView.setUrl(QtCore.QUrl("https://www.alodokter.com/retinopati-diabetik"))
        self.webEngineView.setObjectName("webEngineView")
        self.stackedWidget.addWidget(self.informasi)
        self.setting = QtWidgets.QWidget()
        self.setting.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.setting.setObjectName("setting")
        self.webEngineView_2 = QtWebEngineWidgets.QWebEngineView(self.setting)
        self.webEngineView_2.setGeometry(QtCore.QRect(-1, -1, 1021, 521))
        self.webEngineView_2.setUrl(QtCore.QUrl("https://drive.google.com/file/d/1FS8cbweTg9DbBbCbCCrpdx72bx2RYwLV/view"))
        self.webEngineView_2.setObjectName("webEngineView_2")
        self.frame_5 = QtWidgets.QFrame(self.setting)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 1041, 51))
        self.frame_5.setStyleSheet("\n"
"background-color: rgb(44, 44, 44);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.setting)
        self.frame_6.setGeometry(QtCore.QRect(0, 40, 111, 481))
        self.frame_6.setStyleSheet("\n"
"background-color: rgb(44, 44, 44);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.frame_7 = QtWidgets.QFrame(self.setting)
        self.frame_7.setGeometry(QtCore.QRect(910, 50, 131, 481))
        self.frame_7.setStyleSheet("\n"
"background-color: rgb(44, 44, 44);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.frame_8 = QtWidgets.QFrame(self.setting)
        self.frame_8.setGeometry(QtCore.QRect(120, 510, 801, 141))
        self.frame_8.setStyleSheet("\n"
"background-color: rgb(44, 44, 44);")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.stackedWidget.addWidget(self.setting)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main_item)
        self.right_side_menu = QtWidgets.QFrame(self.main_body)
        self.right_side_menu.setMinimumSize(QtCore.QSize(30, 0))
        self.right_side_menu.setMaximumSize(QtCore.QSize(30, 16777215))
        self.right_side_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.right_side_menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_side_menu.setObjectName("right_side_menu")
        self.label_3 = QtWidgets.QLabel(self.right_side_menu)
        self.label_3.setGeometry(QtCore.QRect(10, 260, 71, 111))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.right_side_menu)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QtCore.QSize(0, 40))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 50))
        self.main_footer.setStyleSheet("QFrame{\n"
"    background-color: rgb(0, 0, 0);\n"
"    border-top-color:1px solid rgb(0, 0, 0);\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.main_footer)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.footer = QtWidgets.QLabel(self.main_footer)
        self.footer.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("News701 BT")
        self.footer.setFont(font)
        self.footer.setStyleSheet("color: rgb(255, 255, 255);")
        self.footer.setObjectName("footer")
        self.horizontalLayout_6.addWidget(self.footer, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_home.setText(_translate("MainWindow", "HOME"))
        self.btn_informasi.setText(_translate("MainWindow", "INFO"))
        self.btn_setting.setText(_translate("MainWindow", "ABOUT"))
        self.original_image.setText(_translate("MainWindow", "Original"))
        self.img_after.setText(_translate("MainWindow", "Preprocessing"))
        self.btn_browse.setText(_translate("MainWindow", "Browse"))
        self.path_dir.setText(_translate("MainWindow", "path/directory"))
        self.label.setText(_translate("MainWindow", "Hasil Deteksi Diabetik Retinopati"))
        self.hasil_deteksi.setText(_translate("MainWindow", "Please Choose File"))
        self.label_3.setText(_translate("MainWindow", "RIGHT MENU"))
        self.footer.setText(_translate("MainWindow", "Created By Wahyu Saputro"))

from PyQt5 import QtWebEngineWidgets
import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

